import type { Metadata } from "next";
import localFont from "next/font/local";
import QueryProvider from '@/providers/QueryProvider';
import { Theme, Flex, Heading } from "@radix-ui/themes";
import StoreProvider from '../providers/Store';
import ToastProvider from '../providers/ToastProvider';
import "./globals.css";
import "@radix-ui/themes/styles.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastProvider>
          <QueryProvider>
            <StoreProvider>
              <Theme>
                <main className="bg-background">
                  <Heading as="h1" className="w-full z-[9999] bg-background text-center text-white py-8">Notification Service</Heading>
                  <Flex>
                    {children}
                  </Flex>
                </main>
              </Theme>
            </StoreProvider>
          </QueryProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
