import type { Metadata } from "next";
import localFont from "next/font/local";
import QueryProvider from '@/providers/QueryProvider';
import { Theme, Flex, Heading } from "@radix-ui/themes";
import NavigationMenu from '../components/NavigationMenu';
import "./globals.css";
import "@radix-ui/themes/styles.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <Theme>
            <main className="bg-background">
              <Heading as="h1" className="w-full z-[9999] bg-background text-center sticky top-0 text-white py-8">SkyCity Casino - Back Office</Heading>
              <Flex>
                <aside className="w-[300px] bg-white border border-r-grey-300">
                  <NavigationMenu />
                </aside>
                <div className="flex-1">
                  {children}
                </div>
              </Flex>
            </main>
          </Theme>
        </QueryProvider>
      </body>
    </html>
  );
}
